version: '2'

services:
    node:
        build:
            context: ./
        image: wmde/query-builder
        volumes:
            - '~/.npm:/.npm'
            - './:/app'
        working_dir: /app

    dev:
        extends:
            service: node
        command: 'npm run serve'
        ports:
            - '${PORT}:${PORT}'
        environment:
            - NODE_ENV=development
