version: '2'

services:
    e2e:
        image: "cypress/included:6.3.0"
        depends_on:
            - dev
        volumes:
            - ./cypress:/cypress
            - ./cypress.json:/cypress.json
        command: "--browser chrome --headless"
        environment:
            - CYPRESS_BASE_URL=http://dev:${PORT}
            - CYPRESS_API_URL=${VUE_APP_WIKIBASE_API_URL}
