on: [push, pull_request]

name: Run cypress
jobs:
  cypress-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: node
      run: docker-compose --env-file .env.example build --build-arg UID=$(id -u) --build-arg GID=$(id -g) node
    - name: Install npm
      run: docker-compose --env-file .env.example run --rm node npm ci
    - name: Run Cypress end-to-end
      run: docker-compose --env-file .env.example -f docker-compose.yml -f docker-compose.e2e.yml up e2e
