name: Test and lint

on: [push]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: npm ci
    - name: Test
      run: npm run test

  unit-test-with-coverage-and-sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install
      run: npm ci
    - name: Test
      run: npm run test:unit -- --coverage
    - name: Setup Sonar Scanner
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      env:
        # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonarcloud.io/
